#!/usr/bin/env bash
set -euo pipefail

GCS_CRIO_SA=${GCS_CRIO_SA:-}
# defaults to gs://cri-o
GCS_BUCKET_NAME=${GCS_BUCKET_NAME:-cri-o}

if [[ -z $GCS_CRIO_SA ]]; then
    echo "Using existing credentials for gsutil"
else
    echo "Activating GCP service account using $GCS_CRIO_SA"
    gcloud auth activate-service-account --key-file=$GCS_CRIO_SA
fi

BUCKET=gs://$GCS_BUCKET_NAME

echo "Uploading artifacts to Google Cloud Bucket"
gsutil cp -n build/bundle/*.tar.gz* $BUCKET/artifacts

# update the latest version marker file for the branch
MARKER=$(git rev-parse --abbrev-ref HEAD)
VERSION=$(git rev-parse HEAD)

# if in detached head state, we assume we're on a tag
if [[ $MARKER == HEAD ]]; then
    # use the major.minor as marker
    VERSION=$(git describe --tags --exact-match)
    MARKER=$(echo "$VERSION" | cut -c 2-5)
fi
echo "$VERSION" >"latest-$MARKER.txt"
gsutil cp "latest-$MARKER.txt" $BUCKET
